### ISSUE TITLE
Conflict es6-shim

### ISSUE THREAD

**Issue by beradrian** [mleko/typescript-object-utils#2]
I'm using `typescript-object-utils` in an Angular 4 project generated with Angular CLI.

If I'm importing 

    import { mergeDeep } from "typescript-object-utils";

I'm getting errors like

> ERROR in .../node_modules/@types/es6-shim/index.d.ts (7,14): Duplicate identifier 'PropertyKey'.

If I'm importing 

    import { mergeDeep } from "typescript-object-utils/src/mergeDeep";

I'm getting errors like

> ERROR in .../node_modules/typescript-object-utils/src/shallowMerge.ts (4,2): Type 'A' is not assignable to type 'A & B'.
>  Type 'A' is not assignable to type 'B'.

I guess it's a conflict when using `es6-shim`.

**Comment by mleko** [comment]
> ERROR in .../node_modules/@types/es6-shim/index.d.ts (7,14): Duplicate identifier 'PropertyKey'.

is resolved by https://github.com/mleko/typescript-object-utils/issues/3

> ERROR in .../node_modules/typescript-object-utils/src/shallowMerge.ts (4,2): Type 'A' is not assignable to type 'A & B'. 
> Type 'A' is not assignable to type 'B'.

is resolved in 860f0b0631e770748dea458cce74c1b64d40ff61

**Comment by mleko** [comment]
Thank you @beradrian
